[Distribution]
Distribution=arch

[Output]
Format=disk
ImageId=arch
SplitArtifacts=partitions,uki
Output=%i_%v_%a

[Content]
Packages=
         archlinux-keyring
         base
         linux
         linux-firmware
Bootable=true
Bootloader=systemd-boot
UnifiedKernelImages=unsigned
InitrdProfiles=plymouth
KernelCommandLine=
        root=dissect
        mount.usr=dissect
        rw
        audit=0
        systemd.image_policy=esp=unprotected:xbootldr=unprotected+unused+absent:usr=signed:root=encrypted+absent:swap=encrypted+unused+absent:home=unprotected+absent:=ignore
        systemd.image_filter=usr=arch_*:usr-verity=arch_*:usr-verity-sig=arch_*:root=arch-*
        ipe.enforce=0
        quiet
[Validation]
SecureBoot=yes
SecureBootAutoEnroll=yes
SignExpectedPcr=yes

[Build]
Incremental=true
