[Content]
Packages=
   	 networkmanager
         gnome
         gnome-initial-setup
RemovePackages=
	 baobab
	 decibels
	 epiphany
	 gnome-calculator
	 gnome-calendar
	 gnome-characters
	 gnome-clocks
	 gnome-connections
	 gnome-contacts
	 gnome-font-viewer
	 gnome-logs
	 gnome-maps
	 gnome-music
	 gnome-system-monitor
	 gnome-text-editor
	 gnome-weather
	 loupe
	 papers
	 showtime
	 simple-scan
	 snapshot
